### ISSUE TITLE
The plugin does not work with xterm and rxvt-unicode under tmux.

### ISSUE THREAD

**Issue by mangust** [jszakmeister/vim-togglecursor#27]
Hi

I just checked with vim:

guake does nothing (OK - the old libvte)
guake with tmux does nothing (Ok too)

konsole - works
konsole under tmux - works

urxvt (rxvt-unicode 9.21) - works
urxvt under tmux does not work (nothing happens).

xterm (297 version) works
xterm under tmux does not work.

I believe that your plugin checks for $KONSOLE_DBUS_SESSION but it does not check for the real terminal emulator under a tmux session. I do not know is it possible at all. Quick search on google didn't help.

**Comment by jszakmeister** [comment]
urxvt I don't expect to work.  The only way to check whether you're running under urxvt is by examining TERM, and TERM if often set to `screen` or `screen-256color`--so the bit we need to detect urxvt isn't there.

As for xterm, it does work--I just checked with version 317.  Is the XTERM_VERSION variable available in your tmux session under xterm?  If not, then there's the problem.

It's a bit more complicated than that though.  tmux captures the environment where it was first started, so if it wasn't started under xterm, then it won't have the variable when you re-join the session under xterm and tmux.  I can't really do much about that, which is why I provide a way for you to skip the auto-detection and outright state what you want.  You can do this by adding a line to your ~/.vimrc:

```vim
    let g:togglecursor_force = 'xterm'
```

That will force of the xterm DECSCUSR-style cursor-changing escape sequences.

> I believe that your plugin checks for $KONSOLE_DBUS_SESSION but it does not check for the real terminal emulator under a tmux session. I do not know is it possible at all. Quick search on google didn't help.

That's because I can't.  If the terminals don't export something useful to the environment, then I can't do the detection.  It's the best thing I had, so it's what I used.  That's also why it's at the end of the list in the detection chain--we only use it as a last resort.

**Comment by mangust** [comment]
Hm... When I launch xterm all $XTERM_* variables are in place, but when then I start xterm they are gone... Maybe something wrong with my .zshrc-* files... I'll check

**Comment by mangust** [comment]
$#$@$*!!!

I removed .Xresources but I didn't reboot X. Sorry very much. The problem is there. I looked and tried and did some fool things and then I again remove my .Xresources and just rebooted. xterm under tmux works. Sorry one more time. Too many hacking and experimenting)

**Comment by jszakmeister** [comment]
No worries!  It looks like I can close this, since there's nothing I can really do about using tmux under urxvt, and there's a workaround for it.
