### ISSUE TITLE
Plugin in Alacritty doesnt work

### ISSUE THREAD

**Issue by C0nrado** [jszakmeister/vim-togglecursor#45]
As by default only, this plugin doenst cause any effects on vim running in Alacritty.

I've changed vim rc to include the 'togglecursor_force' variable, and still nothing comes out.
```

if match($TERM, 'xterm') == 0
     let g:togglecursor_force = 'xterm'
endif
```

I couldn't find much support in general google search. I would appretiate if someone else could help me out.
My $TERM variable currently is xterm-256colors

**Comment by jszakmeister** [comment]
That's the general approach because emitting escape codes to a terminal that doesn't support them can screw up the terminal.  So I'm conservative in the approach.

Does this come before you include the plugin?  It needs to do so.  togglecursor sets another internal variable based on this value, but if it shows up late, it'll have no effect.

Note: checking for xterm is not a good approach for enabling cursor changing.  There are many terminals out there that support a substantial amount of xterm's capability, but not cursor shape changes.  In another environment, togglecursor would emit escape sequence that mess up the user's screen.  If there is something that is specific to Alacritty, then we can add support.  It appears there is an `ALACRITTY_LOG` we could check for, but I don't really love that as an answer.  If it set `TERM_PROGRAM` to something useful, like `"alacritty"`, that'd be great.  Perhaps you can propose that as a merge request.

FWIW, I took your snippet and put it early in my vimrc, and it works quite fine with Alacritty under macOS.

**Comment by C0nrado** [comment]
Hi!!
Now, that's funny. 
For whatever reason I was just headed to update some stuff in my alacritty, and changed the cursor shape ( within terminal config) to block, right after I noticed the cursor was toggling between block and beam shapes (which I almost sure are the plugin's default) in vim as it was supposed to.
When I posted this issue, my cursor shape was set to 'underline' and after I changed it to 'block' the problem kind of sorted itself out...  Maybe alacritty internal config to change cursor shape was messing up with the vim+plugin

**Comment by jszakmeister** [comment]
Oh, that could very well be.  Unfortunately, cursor shape management is lacking across all terminals.  And Vim doesn't really have all the required hooks to properly interrogate the terminal--though that still requires terminals implementing all the right bits, and they don't yet.  So it is rather tough.  My plugin does some clever things to help try and overcome the issues, but when we can't interrogate, it falls on the user to manage things more.  That's part of the reason there are several options to help control it all.

No need to delete the issue.  Glad it's working for you now!
